stages:
  - BasicVars: fast_carpenter.Define
  - ClusterVars: my-analysis.ClusterVars
  - Clusters: my-analysis.ClusterFinder
  - clusDStart: fast_carpenter.BinnedDataframe
  - clusNHits: fast_carpenter.BinnedDataframe

BasicVars:
  variables:
    - isMarley: (Hit_True_GenType == 1) & (Hit_True_MarleyIndex==0)


ClusterVars: {mask: isMarley}

Clusters: { mask: isMarley,  out_var: clusterNHits }

clusDStart:
    binning:
        - {in: DeltaStart, out: clusDStart}

clusNHits:
    binning:
        - {in: clusterNHits, out: clusNHits}

